# Generated by Django 4.1.4 on 2023-01-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='user',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='taskmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
