# Generated by Django 4.1.4 on 2023-01-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('desc', models.TextField()),
                ('type', models.CharField(max_length=225, null=True)),
            ],
        ),
    ]
