# Generated by Django 4.1.4 on 2023-01-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
