# Generated by Django 4.1.4 on 2023-01-19 08:35

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
